# Generated by Django 3.2.16 on 2023-02-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20230223_0823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('id',), 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterModelOptions(
            name='timelog',
            options={'verbose_name': 'TimeLog', 'verbose_name_plural': 'TimeLogs'},
        ),
        migrations.AddField(
            model_name='timelog',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
