# Generated by Django 3.2.16 on 2023-03-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20230227_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='stop',
        ),
    ]
