# Generated by Django 3.2.16 on 2023-02-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timer',
            name='stop',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
