version: '3.9'

volumes:
    internship_postgres:
        name: internship_postgres
    internship_rabbitmq:
        name: internship_rabbitmq


services:
  django:
    container_name: internship_django
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - bash
      - -c
      - |
        python -m internship migrate --no-input
        python -m internship collectstatic --no-input
        python -m internship runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq


  postgres:
    image: postgres:latest
    container_name: internship_postgres
    hostname: postgres.internship.com
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - internship_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  pghero:
    image: ankane/pghero:latest
    container_name: pghero
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@host.docker.internal:${DB_PORT}/${DB_NAME}

  redis:
    container_name: internship_redis
    image: redis:7.0.7-alpine

  rabbitmq:
    container_name: internship_rabbitmq
    hostname: rabbitmq.internship.com
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
      - internship_rabbitmq:/var/lib/rabbitmq


  internship_celery_worker:
    container_name: internship_celery_worker
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: celery -A internship.celery:app worker -l INFO
    depends_on:
      - rabbitmq
      - postgres


  internship_celery_beat:
    container_name: internship_celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env
    command: celery -A internship.celery:app beat -l INFO
    depends_on:
      - rabbitmq
      - postgres
