version: '3.9'

services:
  backend:
    build: .
    volumes:
      - .:/app/backend
    restart: always
    ports:
      - "8000:8000"
    command: make docker-run-dev
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  pghero:
    image: ankane/pghero
    container_name: pghero
    network_mode: host
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

  redis:
    image: redis:7.0.7
    command: redis-server