version: '3.9'

volumes:
    internship_postgres:
        name: internship_postgres


services:
  django:
    container_name: internship_django
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - bash
      - -c
      - |
        python -m internship migrate --no-input
        python -m internship collectstatic --no-input
        python -m internship runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis


  postgres:
    image: postgres:latest
    container_name: internship_postgres
    hostname: postgres.internship.com
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - internship_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  pghero:
    image: ankane/pghero
    container_name: pghero
    network_mode: host
    ports:
      - 8080:8080
    environment:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres


  redis:
    image: redis:7.0.7-alpine


  rabbitmq:
    image: rabbitmq:3.10.7-management-alpine


  celery-worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: madefire/chordtest
    command: ['celery', '-A', 'internship', 'worker', '-l', 'info']
    volumes:
      - ./:/app/
    depends_on:
      - rabbitmq
      - django
      - postgres


  celery-beat-worker:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: madefire/chordtest
    command: ['celery', '-A', 'internship', 'beat', '-l', 'info']
    volumes:
      - ./:/app/
    depends_on:
      - celery-worker
      - rabbitmq
      - django
      - postgres
