[tool.poetry]
name = "python-internship"
version = "0.1.0"
description = ""
authors = ["panasicov"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "3.2.16"
celery = "5.2.7"
django-filter = "22.1"
django-redis = "5.2.0"
djangorestframework = "3.14.0"
djangorestframework-simplejwt = "5.2.2"
django-cors-headers = "3.13.0"
requests = "2.28.1"
drf-yasg = "1.21.4"
drf-util = "1.0.17"
psycopg2-binary = "2.9.5"
faker = "17.5.0"
sentry-sdk = "1.16.0"
amqp = "5.1.1"
asgiref = "3.6.0"
async-timeout = "4.0.2"
attrs = "22.2.0"
billiard = "3.6.4.0"
certifi = "2022.12.7"
cfgv = "3.3.1"
charset-normalizer = "2.1.1"
click = "8.1.3"
click-didyoumean = "0.3.0"
click-plugins = "1.1.1"
click-repl = "0.2.0"
coreapi = "2.3.3"
coreschema = "0.0.4"
distlib = "0.3.6"
executing = "1.2.0"
filelock = "3.9.0"
flake8 = "6.0.0"
identify = "2.5.18"
idna = "3.4"
inflection = "0.5.1"
itypes = "1.2.0"
jinja2 = "3.1.2"
jsonschema = "4.17.3"
kombu = "5.2.4"
markupsafe = "2.1.2"
mccabe = "0.7.0"
nodeenv = "1.7.0"
packaging = "23.0"
platformdirs = "3.0.0"
pre-commit = "3.1.1"
prompt-toolkit = "3.0.38"
pycodestyle = "2.10.0"
pyflakes = "3.0.1"
pyjwt = "2.6.0"
pyrsistent = "0.19.3"
python-dateutil = "2.8.2"
python-dotenv = "1.0.0"
pytz = "2022.7.1"
pyyaml = "6.0"
redis = "4.5.1"
ruamel-yaml = "0.17.21"
ruamel-yaml-clib = "0.2.7"
six = "1.16.0"
sqlparse = "0.4.3"
swagger-spec-validator = "3.0.3"
typing-extensions = "4.5.0"
uritemplate = "4.1.1"
urllib3 = "1.26.14"
varname = "0.11.0"
vine = "5.0.0"
virtualenv = "20.20.0"
wcwidth = "0.2.6"
pip-shims = "^0.7.3"
django-debug-toolbar = "3.8.1"
django-celery-beat = "^2.4.0"
django-celery-results = "^2.4.0"
django-environ = "^0.10.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
